### ISSUE TITLE
Navigation Menu Weird Behavior while Navigating Back and Forth

### ISSUE THREAD

**Issue by louieseno** [EugerBonete/euger-bonete-portfolio#1]
Hi there! I recently came across your portfolio in the React Group and noticed a peculiar issue related to the navigation menus. When navigating back and forth between pages, I encountered some strange behavior that appeared to be connected to the loading of the menu content.

Steps to Reproduce:

1. Visit the portfolio website.
2. Navigate to a different page within the website.
3. Attempt to navigate back to the previous page.
4. Observe the behavior of the navigation menu during the transition.

Expected Behavior:
The navigation menu should function smoothly, allowing seamless navigation between pages without visual glitches or disruptions.

Actual Behavior:
The hero component, the Bear Image, has a glitch effect; the content sometimes loads or displays no content.

Additional Information:
Device: MacBook Pro
Operating System:  macOS Big Sur
Browser: Chrome

**Comment by azkriven16** [comment]
Thank you for the feedback. I appreciate your input, and I will address
the issue asap.

**Comment by EugerBonete** [comment]
fixed
